# Generated by Django 5.1.1 on 2024-09-22 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colloquium', '0003_alter_conversation_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='conversation',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
