# Generated by Django 5.1.1 on 2024-09-08 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleus', '0002_aiprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiprofile',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aiprofile',
            name='hobbies',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aiprofile',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='aiprofile',
            name='personality',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aiprofile',
            name='physical_appearance',
            field=models.TextField(blank=True, null=True),
        ),
    ]
