# Generated by Django 5.1.1 on 2024-09-22 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nucleus', '0004_profile_name_alter_profile_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aiprofile',
            old_name='age',
            new_name='ai_age',
        ),
        migrations.RenameField(
            model_name='aiprofile',
            old_name='hobbies',
            new_name='ai_hobbies',
        ),
        migrations.RenameField(
            model_name='aiprofile',
            old_name='name',
            new_name='ai_name',
        ),
        migrations.RenameField(
            model_name='aiprofile',
            old_name='personality',
            new_name='ai_personality',
        ),
        migrations.RenameField(
            model_name='aiprofile',
            old_name='physical_appearance',
            new_name='ai_physical_appearance',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='age',
            new_name='user_age',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='description',
            new_name='user_description',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='gender',
            new_name='user_gender',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='name',
            new_name='user_name',
        ),
    ]
